/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.flight.project_flight.event;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AlertEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1469631988524320907L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AlertEvent\",\"namespace\":\"com.flight.project_flight.event\",\"fields\":[{\"name\":\"passwordNumber\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"alertId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"message\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"severity\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"alertDate\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"flightNumber\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AlertEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AlertEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AlertEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AlertEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AlertEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AlertEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AlertEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AlertEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AlertEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence passwordNumber;
  private java.lang.CharSequence email;
  private java.lang.CharSequence firstName;
  private java.lang.CharSequence lastName;
  private java.lang.Long alertId;
  private java.lang.CharSequence message;
  private java.lang.CharSequence severity;
  private java.lang.CharSequence alertDate;
  private java.lang.CharSequence flightNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AlertEvent() {}

  /**
   * All-args constructor.
   * @param passwordNumber The new value for passwordNumber
   * @param email The new value for email
   * @param firstName The new value for firstName
   * @param lastName The new value for lastName
   * @param alertId The new value for alertId
   * @param message The new value for message
   * @param severity The new value for severity
   * @param alertDate The new value for alertDate
   * @param flightNumber The new value for flightNumber
   */
  public AlertEvent(java.lang.CharSequence passwordNumber, java.lang.CharSequence email, java.lang.CharSequence firstName, java.lang.CharSequence lastName, java.lang.Long alertId, java.lang.CharSequence message, java.lang.CharSequence severity, java.lang.CharSequence alertDate, java.lang.CharSequence flightNumber) {
    this.passwordNumber = passwordNumber;
    this.email = email;
    this.firstName = firstName;
    this.lastName = lastName;
    this.alertId = alertId;
    this.message = message;
    this.severity = severity;
    this.alertDate = alertDate;
    this.flightNumber = flightNumber;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return passwordNumber;
    case 1: return email;
    case 2: return firstName;
    case 3: return lastName;
    case 4: return alertId;
    case 5: return message;
    case 6: return severity;
    case 7: return alertDate;
    case 8: return flightNumber;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: passwordNumber = (java.lang.CharSequence)value$; break;
    case 1: email = (java.lang.CharSequence)value$; break;
    case 2: firstName = (java.lang.CharSequence)value$; break;
    case 3: lastName = (java.lang.CharSequence)value$; break;
    case 4: alertId = (java.lang.Long)value$; break;
    case 5: message = (java.lang.CharSequence)value$; break;
    case 6: severity = (java.lang.CharSequence)value$; break;
    case 7: alertDate = (java.lang.CharSequence)value$; break;
    case 8: flightNumber = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'passwordNumber' field.
   * @return The value of the 'passwordNumber' field.
   */
  public java.lang.CharSequence getPasswordNumber() {
    return passwordNumber;
  }


  /**
   * Sets the value of the 'passwordNumber' field.
   * @param value the value to set.
   */
  public void setPasswordNumber(java.lang.CharSequence value) {
    this.passwordNumber = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return The value of the 'firstName' field.
   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }


  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return The value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }


  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'alertId' field.
   * @return The value of the 'alertId' field.
   */
  public java.lang.Long getAlertId() {
    return alertId;
  }


  /**
   * Sets the value of the 'alertId' field.
   * @param value the value to set.
   */
  public void setAlertId(java.lang.Long value) {
    this.alertId = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'severity' field.
   * @return The value of the 'severity' field.
   */
  public java.lang.CharSequence getSeverity() {
    return severity;
  }


  /**
   * Sets the value of the 'severity' field.
   * @param value the value to set.
   */
  public void setSeverity(java.lang.CharSequence value) {
    this.severity = value;
  }

  /**
   * Gets the value of the 'alertDate' field.
   * @return The value of the 'alertDate' field.
   */
  public java.lang.CharSequence getAlertDate() {
    return alertDate;
  }


  /**
   * Sets the value of the 'alertDate' field.
   * @param value the value to set.
   */
  public void setAlertDate(java.lang.CharSequence value) {
    this.alertDate = value;
  }

  /**
   * Gets the value of the 'flightNumber' field.
   * @return The value of the 'flightNumber' field.
   */
  public java.lang.CharSequence getFlightNumber() {
    return flightNumber;
  }


  /**
   * Sets the value of the 'flightNumber' field.
   * @param value the value to set.
   */
  public void setFlightNumber(java.lang.CharSequence value) {
    this.flightNumber = value;
  }

  /**
   * Creates a new AlertEvent RecordBuilder.
   * @return A new AlertEvent RecordBuilder
   */
  public static com.flight.project_flight.event.AlertEvent.Builder newBuilder() {
    return new com.flight.project_flight.event.AlertEvent.Builder();
  }

  /**
   * Creates a new AlertEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AlertEvent RecordBuilder
   */
  public static com.flight.project_flight.event.AlertEvent.Builder newBuilder(com.flight.project_flight.event.AlertEvent.Builder other) {
    if (other == null) {
      return new com.flight.project_flight.event.AlertEvent.Builder();
    } else {
      return new com.flight.project_flight.event.AlertEvent.Builder(other);
    }
  }

  /**
   * Creates a new AlertEvent RecordBuilder by copying an existing AlertEvent instance.
   * @param other The existing instance to copy.
   * @return A new AlertEvent RecordBuilder
   */
  public static com.flight.project_flight.event.AlertEvent.Builder newBuilder(com.flight.project_flight.event.AlertEvent other) {
    if (other == null) {
      return new com.flight.project_flight.event.AlertEvent.Builder();
    } else {
      return new com.flight.project_flight.event.AlertEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for AlertEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AlertEvent>
    implements org.apache.avro.data.RecordBuilder<AlertEvent> {

    private java.lang.CharSequence passwordNumber;
    private java.lang.CharSequence email;
    private java.lang.CharSequence firstName;
    private java.lang.CharSequence lastName;
    private java.lang.Long alertId;
    private java.lang.CharSequence message;
    private java.lang.CharSequence severity;
    private java.lang.CharSequence alertDate;
    private java.lang.CharSequence flightNumber;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.flight.project_flight.event.AlertEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.passwordNumber)) {
        this.passwordNumber = data().deepCopy(fields()[0].schema(), other.passwordNumber);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.firstName)) {
        this.firstName = data().deepCopy(fields()[2].schema(), other.firstName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.lastName)) {
        this.lastName = data().deepCopy(fields()[3].schema(), other.lastName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.alertId)) {
        this.alertId = data().deepCopy(fields()[4].schema(), other.alertId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.message)) {
        this.message = data().deepCopy(fields()[5].schema(), other.message);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.severity)) {
        this.severity = data().deepCopy(fields()[6].schema(), other.severity);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.alertDate)) {
        this.alertDate = data().deepCopy(fields()[7].schema(), other.alertDate);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.flightNumber)) {
        this.flightNumber = data().deepCopy(fields()[8].schema(), other.flightNumber);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing AlertEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.flight.project_flight.event.AlertEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.passwordNumber)) {
        this.passwordNumber = data().deepCopy(fields()[0].schema(), other.passwordNumber);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.firstName)) {
        this.firstName = data().deepCopy(fields()[2].schema(), other.firstName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lastName)) {
        this.lastName = data().deepCopy(fields()[3].schema(), other.lastName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.alertId)) {
        this.alertId = data().deepCopy(fields()[4].schema(), other.alertId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.message)) {
        this.message = data().deepCopy(fields()[5].schema(), other.message);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.severity)) {
        this.severity = data().deepCopy(fields()[6].schema(), other.severity);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.alertDate)) {
        this.alertDate = data().deepCopy(fields()[7].schema(), other.alertDate);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.flightNumber)) {
        this.flightNumber = data().deepCopy(fields()[8].schema(), other.flightNumber);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'passwordNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getPasswordNumber() {
      return passwordNumber;
    }


    /**
      * Sets the value of the 'passwordNumber' field.
      * @param value The value of 'passwordNumber'.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder setPasswordNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.passwordNumber = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'passwordNumber' field has been set.
      * @return True if the 'passwordNumber' field has been set, false otherwise.
      */
    public boolean hasPasswordNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'passwordNumber' field.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder clearPasswordNumber() {
      passwordNumber = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.email = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder clearEmail() {
      email = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }


    /**
      * Sets the value of the 'firstName' field.
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.firstName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'firstName' field.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }


    /**
      * Sets the value of the 'lastName' field.
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.lastName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'lastName' field.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'alertId' field.
      * @return The value.
      */
    public java.lang.Long getAlertId() {
      return alertId;
    }


    /**
      * Sets the value of the 'alertId' field.
      * @param value The value of 'alertId'.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder setAlertId(java.lang.Long value) {
      validate(fields()[4], value);
      this.alertId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'alertId' field has been set.
      * @return True if the 'alertId' field has been set, false otherwise.
      */
    public boolean hasAlertId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'alertId' field.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder clearAlertId() {
      alertId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.message = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder clearMessage() {
      message = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'severity' field.
      * @return The value.
      */
    public java.lang.CharSequence getSeverity() {
      return severity;
    }


    /**
      * Sets the value of the 'severity' field.
      * @param value The value of 'severity'.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder setSeverity(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.severity = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'severity' field has been set.
      * @return True if the 'severity' field has been set, false otherwise.
      */
    public boolean hasSeverity() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'severity' field.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder clearSeverity() {
      severity = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'alertDate' field.
      * @return The value.
      */
    public java.lang.CharSequence getAlertDate() {
      return alertDate;
    }


    /**
      * Sets the value of the 'alertDate' field.
      * @param value The value of 'alertDate'.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder setAlertDate(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.alertDate = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'alertDate' field has been set.
      * @return True if the 'alertDate' field has been set, false otherwise.
      */
    public boolean hasAlertDate() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'alertDate' field.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder clearAlertDate() {
      alertDate = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'flightNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getFlightNumber() {
      return flightNumber;
    }


    /**
      * Sets the value of the 'flightNumber' field.
      * @param value The value of 'flightNumber'.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder setFlightNumber(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.flightNumber = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'flightNumber' field has been set.
      * @return True if the 'flightNumber' field has been set, false otherwise.
      */
    public boolean hasFlightNumber() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'flightNumber' field.
      * @return This builder.
      */
    public com.flight.project_flight.event.AlertEvent.Builder clearFlightNumber() {
      flightNumber = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AlertEvent build() {
      try {
        AlertEvent record = new AlertEvent();
        record.passwordNumber = fieldSetFlags()[0] ? this.passwordNumber : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.email = fieldSetFlags()[1] ? this.email : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.firstName = fieldSetFlags()[2] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.lastName = fieldSetFlags()[3] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.alertId = fieldSetFlags()[4] ? this.alertId : (java.lang.Long) defaultValue(fields()[4]);
        record.message = fieldSetFlags()[5] ? this.message : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.severity = fieldSetFlags()[6] ? this.severity : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.alertDate = fieldSetFlags()[7] ? this.alertDate : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.flightNumber = fieldSetFlags()[8] ? this.flightNumber : (java.lang.CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AlertEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<AlertEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AlertEvent>
    READER$ = (org.apache.avro.io.DatumReader<AlertEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.passwordNumber);

    out.writeString(this.email);

    out.writeString(this.firstName);

    out.writeString(this.lastName);

    if (this.alertId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.alertId);
    }

    if (this.message == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.message);
    }

    if (this.severity == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.severity);
    }

    if (this.alertDate == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.alertDate);
    }

    if (this.flightNumber == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.flightNumber);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.passwordNumber = in.readString(this.passwordNumber instanceof Utf8 ? (Utf8)this.passwordNumber : null);

      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

      this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);

      this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.alertId = null;
      } else {
        this.alertId = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.message = null;
      } else {
        this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.severity = null;
      } else {
        this.severity = in.readString(this.severity instanceof Utf8 ? (Utf8)this.severity : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.alertDate = null;
      } else {
        this.alertDate = in.readString(this.alertDate instanceof Utf8 ? (Utf8)this.alertDate : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.flightNumber = null;
      } else {
        this.flightNumber = in.readString(this.flightNumber instanceof Utf8 ? (Utf8)this.flightNumber : null);
      }

    } else {
      for (int i = 0; i < 9; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.passwordNumber = in.readString(this.passwordNumber instanceof Utf8 ? (Utf8)this.passwordNumber : null);
          break;

        case 1:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        case 2:
          this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);
          break;

        case 3:
          this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.alertId = null;
          } else {
            this.alertId = in.readLong();
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.message = null;
          } else {
            this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.severity = null;
          } else {
            this.severity = in.readString(this.severity instanceof Utf8 ? (Utf8)this.severity : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.alertDate = null;
          } else {
            this.alertDate = in.readString(this.alertDate instanceof Utf8 ? (Utf8)this.alertDate : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.flightNumber = null;
          } else {
            this.flightNumber = in.readString(this.flightNumber instanceof Utf8 ? (Utf8)this.flightNumber : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










