server:
  port: 8080
spring:
  application:
    name: flight-management-service

  datasource:
    url: jdbc:mysql://localhost:3306/flights?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      initialization-fail-timeout: 60000

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      client-id: flight-management-service-producer
      retries: 5
      acks: all
      retry-backoff-ms: 100
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        max.request.size: 200000000
        schema.registry.url: http://localhost:8081
        request.timeout.ms: 120000
        metadata.fetch.timeout.ms: 120000
        metric.reporters: ""
        metrics.recording.level: NONE
    template:
      default-topic: event-placed

    topic:
      flight-events: event-placed

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs

jwt:
  secret: ${JWT_SECRET:votre-secret}
  accessToken:
    expiration: ${JWT_ACCESS_EXP:900000}
  refreshToken:
    expiration: ${JWT_REFRESH_EXP:604800000}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-headers: Authorization, Content-Type

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG
    org.apache.kafka.clients.NetworkClient: DEBUG
    org.springframework.mail: DEBUG
    jakarta.mail: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
