server:
  port: 8081

spring:
  application:
    name: flight-management-service

  datasource:
    url: jdbc:mysql://localhost:3307/flights?useUnicode=true&characterEncoding=UTF-8
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      client-id: flight-management-service-producer
      retries: 5
      acks: all
      retry-backoff-ms: 100
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        max.request.size: 200000000
        schema.registry.url: http://schema-registry:8091
        request.timeout.ms: 120000
        metadata.fetch.timeout.ms: 120000

    template:
      default-topic: event-placed

    topic:
      flight-events: event-placed

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: "kC7g8VvePaKZ6FSrkL0O3pNEakjWwRRU8GJ0aM1cyYwpWs22cD/sGfVrmF84l9ptIPlv6Fh7xn2OxAQgZ9yH/JhKLmpeXhWwXyXhUq6uW/k="
  accessToken:
    expiration: 900000
  refreshToken:
    expiration: 604800000

cors:
  allowed-origins: http://localhost:4200
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-headers: Authorization, Content-Type

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always



